const state={view:'login',loggedIn:false,cart:[],category:'全部',selected:null,selectedOrder:null,detail:{rice:'正常',extras:[],qty:1},source:'現場外賣',payment:'現金',orderTab:'新訂單',soldoutTab:'全部',tables:{1:'空枱',2:'使用中',3:'預約',4:'空枱',5:'清潔中',6:'空枱',7:'空枱',8:'使用中'}};
const products=[
{id:'F4',name:'F4 招牌飯糰套餐',price:45,cat:'套餐',desc:'招牌紫米飯糰＋小食＋飲品',available:true},
{id:'R01',name:'三文魚飯團',price:28,cat:'飯團',desc:'紫米、三文魚、粟米、紫菜',available:true},
{id:'R02',name:'照燒雞肉飯團',price:30,cat:'飯團',desc:'紫米、照燒雞肉、紫菜',available:true},
{id:'R03',name:'牛肉飯團',price:32,cat:'飯團',desc:'紫米、牛肉、粟米、紫菜',available:true},
{id:'B12',name:'肉燥便當',price:48,cat:'便當',desc:'肉燥、配菜、蛋、白飯',available:true},
{id:'S01',name:'炸雞塊',price:22,cat:'小食',desc:'配蜜糖芥末醬',available:false},
{id:'D01',name:'凍檸茶',price:18,cat:'飲品',desc:'可選冰量及甜度',available:true}
];
const orders=[
{id:'P057',source:'現場外賣',status:'新訂單',time:'11:30',total:128,customer:'陳先生',phone:'9123 4567',items:['三文魚飯團 ×2','照燒雞肉飯團 ×1','凍檸茶 ×1','炸雞塊 ×1'],note:'不要芥末'},
{id:'P056',source:'WhatsApp',status:'新訂單',time:'11:28',total:176,customer:'李小姐',phone:'9876 1234',items:['F4 招牌飯糰套餐 ×2'],note:'盡快'},
{id:'P055',source:'Keeta',status:'待處理',time:'11:25',total:98,customer:'平台客人',phone:'—',items:['肉燥便當 ×2'],note:''},
{id:'P054',source:'堂食 · 3號枱',status:'待取餐',time:'11:20',total:156,customer:'堂食',phone:'—',items:['牛肉飯團 ×2','凍檸茶 ×2'],note:''}
];
const nav=[['dashboard','⌂','工作台'],['menu','◩','點單'],['orders','▤','訂單'],['dine','♧','堂食'],['more','☰','更多']];
const money=n=>`$${Number(n).toFixed(1)}`;
const cartTotal=()=>state.cart.reduce((s,x)=>s+x.total,0);
const cartQty=()=>state.cart.reduce((s,x)=>s+x.qty,0);
function setView(view){state.view=view;render();scrollTo(0,0)}
function toggleExtra(name){state.detail.extras.includes(name)?state.detail.extras=state.detail.extras.filter(x=>x!==name):state.detail.extras.push(name);render()}
function addConfigured(){const p=state.selected;const extra=state.detail.extras.length*3;const qty=state.detail.qty;state.cart.push({...p,qty,rice:state.detail.rice,extras:[...state.detail.extras],total:(p.price+extra)*qty});state.detail={rice:'正常',extras:[],qty:1};setView('menu')}
function navHtml(){return `<nav class="bottomnav">${nav.map(([id,icon,label])=>`<button class="navbtn ${state.view===id?'active':''}" data-view="${id}"><span>${icon}</span>${label}</button>`).join('')}</nav>`}
function topbar(title,back=false,action=''){return `<header class="topbar">${back?'<button class="iconbtn" data-back>‹</button>':'<div></div>'}<h1>${title}</h1><button class="iconbtn">${action}</button></header>`}
function login(){return `<main class="login-page"><section class="brand-block"><div class="logo-mark">🍙</div><div class="brand-name">More Fun</div><div class="brand-sub">SMM 點單系統</div></section><section class="login-card"><label>帳號<input id="login-user" autocomplete="username" placeholder="請輸入帳號"></label><label>密碼<div class="password-wrap"><input id="login-pass" type="password" autocomplete="current-password" placeholder="請輸入密碼"><span>◉</span></div></label><button class="primary wide" id="login-btn">登入</button><div class="login-meta"><label><input type="checkbox"> 記住我</label><button class="textbtn">忘記密碼？</button></div></section><footer>© 2026 More Fun</footer></main>`}
function dashboard(){return `${topbar('工作台',false,'♧')}<main class="content"><section class="system-card"><h2>系統狀態</h2><div class="system-row"><span><i class="dot green"></i>SMT 主機</span><b>在線 ›</b></div><div class="system-row"><span><i class="dot green"></i>打印服務</span><b>正常 ›</b></div></section><h2 class="section-heading">今日摘要</h2><section class="summary-grid"><article><span>新訂單</span><b>8</b></article><article><span>待處理</span><b class="blue">12</b></article><article><span>堂食使用中</span><b class="green-text">5</b></article><article><span>待取餐</span><b class="orange-text">7</b></article></section><article class="revenue-card"><div><span>今日營業額</span><b>$8,750.00</b></div><small>較昨日 <em>+12.5%</em></small></article><h2 class="section-heading">快速操作</h2><section class="quick-grid"><button data-view="menu">▣<span>現場點單</span></button><button data-view="menu">☎<span>電話／WhatsApp</span></button><button data-view="dine">♧<span>堂食開枱</span></button><button data-view="orders">▤<span>處理訂單</span></button><button data-view="soldout">▧<span>售罄管理</span></button><button data-view="reports">▥<span>報表總覽</span></button></section></main>${navHtml()}`}
function menu(){const cats=['全部','飯團','便當','小食','飲品'];const filtered=state.category==='全部'?products:products.filter(p=>p.cat===state.category);return `${topbar('點單',false,'⌕')}<main class="content menu-content"><div class="searchbox">⌕ 搜尋商品名稱或編號</div><div class="category-row">${cats.map(c=>`<button class="${state.category===c?'active':''}" data-cat="${c}">${c}</button>`).join('')}</div><section class="menu-list">${filtered.map(p=>`<article class="menu-item ${!p.available?'disabled':''}" data-product="${p.id}"><div class="food-thumb">🍙</div><div class="menu-copy"><h3>${p.name}</h3><p>${p.desc}</p><b>${p.available?money(p.price):'暫停售罄'}</b></div><button class="add-round" data-product="${p.id}" ${!p.available?'disabled':''}>＋</button></article>`).join('')}</section></main>${state.cart.length?`<button class="cartbar" data-view="cart"><span>🛒 購物車　${cartQty()}件</span><strong>${money(cartTotal())}</strong></button>`:''}${navHtml()}`}
function detail(){const p=state.selected;if(!p)return menu();const extraPrice=state.detail.extras.length*3;return `${topbar(p.name,true,'⋯')}<main class="content detail-page"><div class="hero-food">🍙</div><div class="detail-head"><div><h2>${p.name}</h2><p>${p.desc}</p></div><b>${money(p.price)}</b></div><section class="option-block"><h3>飯量 <em>必選</em></h3><div class="segmented">${['正常','少飯 -$2','多飯 +$2'].map(x=>`<button class="${state.detail.rice===x?'active':''}" data-rice="${x}">${x}</button>`).join('')}</div></section><section class="option-block"><h3>加配 <small>可選</small></h3>${['加蛋','加芝士','加粟米'].map(x=>`<label class="check-row"><input type="checkbox" data-extra="${x}" ${state.detail.extras.includes(x)?'checked':''}><span>${x}</span><b>+$3</b></label>`).join('')}</section><section class="option-block"><h3>備註</h3><textarea placeholder="請輸入備註（例如：不要蔥）"></textarea></section><div class="qty-row"><span>數量</span><div><button data-qty="-1">−</button><b>${state.detail.qty}</b><button data-qty="1">＋</button></div></div><button class="primary wide sticky-action" id="add-configured">加入購物車　${money((p.price+extraPrice)*state.detail.qty)}</button></main>`}
function cart(){return `${topbar('購物車',true,'清空')}<main class="content cart-page"><section class="cart-list">${state.cart.length?state.cart.map((x,i)=>`<article class="cart-item"><div class="food-thumb">🍙</div><div class="cart-copy"><h3>${x.name}</h3><p>${x.rice}${x.extras.length?' · '+x.extras.join(' · '):''}</p><div><b>${money(x.total)}</b><span>×${x.qty}</span></div></div><button class="remove" data-remove="${i}">×</button></article>`).join(''):'<div class="empty-state">購物車未有餐點</div>'}</section>${state.cart.length?`<section class="totals"><div><span>小計</span><b>${money(cartTotal())}</b></div><div><span>外賣盒費</span><b>$2.0</b></div><div class="grand"><span>總計</span><b>${money(cartTotal()+2)}</b></div></section><div class="cart-actions"><button class="secondary" data-view="menu">繼續選購</button><button class="primary" data-view="checkout">確認訂單</button></div>`:''}</main>`}
function checkout(){return `${topbar('確認訂單',true,'')}<main class="content checkout-page"><section class="option-block"><h3>訂單來源</h3><div class="choice-grid">${['現場外賣','電話','WhatsApp','App','Keeta','Foodpanda','堂食'].map(x=>`<button class="${state.source===x?'active':''}" data-source="${x}">${x}</button>`).join('')}</div></section><section class="option-block"><h3>付款方式</h3><div class="choice-grid">${['現金','支付寶','微信支付','FPS','PayMe','八達通'].map(x=>`<button class="${state.payment===x?'active':''}" data-payment="${x}">${x}</button>`).join('')}</div></section><section class="option-block"><h3>客人資料</h3><input placeholder="客人姓名"><input placeholder="電話號碼"><textarea placeholder="備註"></textarea></section><section class="totals"><div class="grand"><span>總計</span><b>${money(cartTotal()+2)}</b></div></section><button class="primary wide" id="submit-order">下一步：建立訂單</button></main>`}
function success(){return `${topbar('訂單建立成功')}<main class="content success-page"><div class="success-icon">✓</div><h2>訂單已建立！</h2><p>訂單編號</p><strong>P058</strong><div class="success-note">SMT 已收到訂單<br>打印工作已建立</div><button class="secondary wide" data-view="orderDetail">查看訂單詳情</button><button class="secondary wide" data-view="menu">再開新單</button><button class="primary wide" data-view="dashboard">返回工作台</button></main>`}
function ordersPage(){const tabs=['新訂單','待處理','待取餐','全部'];const list=state.orderTab==='全部'?orders:orders.filter(o=>o.status===state.orderTab);return `${topbar('訂單列表',false,'⌕')}<main class="content"><div class="category-row order-tabs">${tabs.map(t=>`<button class="${state.orderTab===t?'active':''}" data-order-tab="${t}">${t}</button>`).join('')}</div><section class="order-list">${list.map(o=>`<button class="order-card" data-order="${o.id}"><div><strong>${o.id}</strong><span>${o.time}</span></div><h3>${o.source}</h3><p>${o.items.length}項餐點</p><footer><b>${money(o.total)}</b><em class="status ${o.status}">${o.status}</em></footer></button>`).join('')}</section></main>${navHtml()}`}
function orderDetail(){const o=state.selectedOrder||orders[0];return `${topbar('訂單詳情',true,'⋯')}<main class="content"><section class="order-hero"><div><h2>${o.id}</h2><span class="status ${o.status}">${o.status}</span></div><dl><div><dt>訂單來源</dt><dd>${o.source}</dd></div><div><dt>下單時間</dt><dd>${o.time}</dd></div><div><dt>客人姓名</dt><dd>${o.customer}</dd></div><div><dt>電話號碼</dt><dd>${o.phone}</dd></div><div><dt>備註</dt><dd>${o.note||'—'}</dd></div></dl></section><section class="option-block"><h3>商品明細</h3>${o.items.map(i=>`<div class="detail-line"><span>${i}</span><b></b></div>`).join('')}<div class="detail-line total-line"><span>總計</span><b>${money(o.total)}</b></div></section><div class="triple-actions"><button class="primary">接單</button><button class="secondary">修改</button><button class="secondary danger">取消</button></div></main>`}
function dine(){return `${topbar('堂食管理',false,'')}<main class="content"><div class="legend"><span><i class="dot green"></i>空枱</span><span><i class="dot orange"></i>使用中</span><span><i class="dot blue-dot"></i>預約</span><span><i class="dot gray"></i>清潔中</span></div><section class="table-grid">${Object.entries(state.tables).map(([n,s])=>`<button class="table-card ${s}" data-table="${n}"><strong>${n}號枱</strong><span>${s}</span></button>`).join('')}</section><button class="secondary wide" data-new-table>新增堂食訂單</button></main>${navHtml()}`}
function soldout(){const cats=['全部','飯團','便當','小食','飲品'];const list=state.soldoutTab==='全部'?products:products.filter(p=>p.cat===state.soldoutTab);return `${topbar('售罄管理',true,'')}<main class="content"><div class="searchbox">⌕ 搜尋商品名稱</div><div class="category-row">${cats.map(c=>`<button class="${state.soldoutTab===c?'active':''}" data-soldout-tab="${c}">${c}</button>`).join('')}</div><section class="soldout-list">${list.map(p=>`<article><div><h3>${p.name}</h3><p>${p.available?'供應中':'售罄中'}</p></div><label class="switch"><input type="checkbox" data-availability="${p.id}" ${p.available?'checked':''}><span></span></label></article>`).join('')}</section><div class="bulk-actions"><button class="secondary">全選</button><button class="secondary">取消全選</button><button class="primary">套用狀態</button></div></main>`}
function reports(){return `${topbar('報表總覽',true,'')}<main class="content"><article class="report-hero"><span>今日營業額</span><strong>$8,750.00</strong><small>較昨日 <em>+12.5%</em></small><div class="sparkline">╭╮╭─╮╭──╮╭╮</div></article><section class="report-list">${[['▥','營業額報表'],['▤','渠道報表'],['▣','付款報表'],['◩','商品報表'],['◫','日結報表'],['♧','異常報表']].map(([i,t])=>`<button><span>${i}</span><b>${t}</b><em>›</em></button>`).join('')}</section></main>${navHtml()}`}
function printJobs(){return `${topbar('打印工作',true,'')}<main class="content"><section class="system-card"><div class="system-row"><span><i class="dot green"></i>SMT 打印主機</span><b>在線</b></div><div class="system-row"><span><i class="dot green"></i>收據機</span><b>正常</b></div><div class="system-row"><span><i class="dot orange"></i>標籤機 2</span><b>待重試</b></div></section><section class="order-list"><article class="job-card"><div><strong>P057 · 標籤機2</strong><span>11:31</span></div><p>第2次重試失敗</p><button class="primary">重新打印</button></article><article class="job-card"><div><strong>P056 · 後廚機1</strong><span>11:29</span></div><p>打印成功</p></article></section></main>`}
function more(){return `${topbar('更多',false,'')}<main class="content more-list">${[['system','◌','系統診斷'],['printJobs','▧','打印工作管理'],['soldout','▨','售罄管理'],['reservations','▤','預約訂單管理'],['customers','♧','客戶管理'],['password','⌁','修改密碼'],['logout','⇥','登出']].map(([v,i,t])=>`<button data-more="${v}"><span>${i}</span><b>${t}</b><em>›</em></button>`).join('')}</main>${navHtml()}`}
function generic(title,text){return `${topbar(title,true,'')}<main class="content"><article class="system-card"><p>${text}</p></article></main>`}
function render(){let page=state.view==='login'?login():state.view==='dashboard'?dashboard():state.view==='menu'?menu():state.view==='detail'?detail():state.view==='cart'?cart():state.view==='checkout'?checkout():state.view==='success'?success():state.view==='orders'?ordersPage():state.view==='orderDetail'?orderDetail():state.view==='dine'?dine():state.view==='soldout'?soldout():state.view==='reports'?reports():state.view==='printJobs'?printJobs():state.view==='more'?more():generic('功能頁','此功能已建立入口，等待接駁正式資料。');document.querySelector('#app').innerHTML=`<div class="app ${state.view}">${page}</div>`;bind()}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>historyBack());document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;render()});document.querySelectorAll('[data-product]').forEach(b=>b.onclick=e=>{e.stopPropagation();const p=products.find(p=>p.id===b.dataset.product);if(!p.available)return;state.selected=p;state.view='detail';render()});document.querySelectorAll('[data-rice]').forEach(b=>b.onclick=()=>{state.detail.rice=b.dataset.rice;render()});document.querySelectorAll('[data-extra]').forEach(b=>b.onchange=()=>toggleExtra(b.dataset.extra));document.querySelectorAll('[data-qty]').forEach(b=>b.onclick=()=>{state.detail.qty=Math.max(1,state.detail.qty+Number(b.dataset.qty));render()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.cart.splice(Number(b.dataset.remove),1);render()});document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{state.source=b.dataset.source;render()});document.querySelectorAll('[data-payment]').forEach(b=>b.onclick=()=>{state.payment=b.dataset.payment;render()});document.querySelectorAll('[data-order-tab]').forEach(b=>b.onclick=()=>{state.orderTab=b.dataset.orderTab;render()});document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{state.selectedOrder=orders.find(o=>o.id===b.dataset.order);setView('orderDetail')});document.querySelectorAll('[data-table]').forEach(b=>b.onclick=()=>{const n=b.dataset.table;state.tables[n]=state.tables[n]==='空枱'?'使用中':'空枱';render()});document.querySelectorAll('[data-soldout-tab]').forEach(b=>b.onclick=()=>{state.soldoutTab=b.dataset.soldoutTab;render()});document.querySelectorAll('[data-availability]').forEach(b=>b.onchange=()=>{const p=products.find(p=>p.id===b.dataset.availability);p.available=b.checked;render()});document.querySelectorAll('[data-more]').forEach(b=>b.onclick=()=>{const v=b.dataset.more;if(v==='logout'){state.loggedIn=false;setView('login')}else setView(v)});const loginBtn=document.querySelector('#login-btn');if(loginBtn)loginBtn.onclick=()=>{state.loggedIn=true;setView('dashboard')};const addBtn=document.querySelector('#add-configured');if(addBtn)addBtn.onclick=addConfigured;const submit=document.querySelector('#submit-order');if(submit)submit.onclick=()=>{state.cart=[];setView('success')}}
function historyBack(){const map={detail:'menu',cart:'menu',checkout:'cart',success:'dashboard',orderDetail:'orders',soldout:'more',reports:'dashboard',printJobs:'more',reservations:'more',customers:'more',password:'more',system:'more'};setView(map[state.view]||'dashboard')}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
render();