const state={view:'dashboard',cart:[],category:'人氣推薦'};
const products=[
{id:'F4',name:'F4 招牌飯糰套餐',price:45,cat:'人氣推薦'},
{id:'BENTO12',name:'肉燥便當',price:48,cat:'便當'},
{id:'R01',name:'照燒雞飯糰',price:43,cat:'飯糰'},
{id:'S01',name:'蜜糖芥末薯角',price:24,cat:'小食'},
{id:'D01',name:'台式奶茶',price:20,cat:'飲品'},
{id:'SALAD01',name:'紫米能量沙律',price:52,cat:'沙律'}
];
const nav=[['dashboard','工作台'],['menu','點單'],['orders','訂單'],['dine','堂食'],['more','更多']];
const money=n=>`$${n}`;
const cartTotal=()=>state.cart.reduce((s,x)=>s+x.price*x.qty,0);
function setView(view){state.view=view;render();scrollTo(0,0)}
function addProduct(id){const p=products.find(x=>x.id===id);const item=state.cart.find(x=>x.id===id);item?item.qty++:state.cart.push({...p,qty:1});render()}
function navHtml(){return `<nav class="bottomnav">${nav.map(([id,label])=>`<button class="navbtn ${state.view===id?'active':''}" data-view="${id}">${label}</button>`).join('')}</nav>`}
function header(title,sub='磨飯 SMM'){return `<header class="topbar"><div class="eyebrow">${sub}</div><h1>${title}</h1></header>`}
function dashboard(){return `${header('工作台')}<main class="content"><section class="status-grid"><article class="card"><div class="label">待處理訂單</div><div class="metric">6</div></article><article class="card"><div class="label">打印異常</div><div class="metric">1</div></article><article class="card"><div class="label">今日訂單</div><div class="metric">42</div></article><article class="card"><div class="label">今日營業額</div><div class="metric">$3,286</div></article></section><div class="section-title"><h2>快速操作</h2></div><section class="quick-grid"><button class="btn primary" data-view="menu">開新單</button><button class="btn" data-view="orders">處理訂單</button><button class="btn" data-view="dine">堂食開枱</button><button class="btn" data-view="more">售罄管理</button></section><div class="section-title"><h2>最新訂單</h2></div><section class="list"><article class="card order-row"><div><strong>P057</strong><div class="label">網站 · 3件</div></div><span class="badge">待確認</span></article><article class="card order-row"><div><strong>A023</strong><div class="label">現場外賣 · 2件</div></div><span class="badge">製作中</span></article></section></main>`}
function menu(){const cats=['人氣推薦','飯糰','套餐','便當','小食','飲品','沙律'];const filtered=state.category==='人氣推薦'?products:products.filter(p=>p.cat===state.category);return `${header('點單','選餐後加入購物車')}<main class="content"><div class="category-row">${cats.map(c=>`<button class="chip ${state.category===c?'active':''}" data-cat="${c}">${c}</button>`).join('')}</div><section class="product-grid">${filtered.map(p=>`<article class="card product"><div><div class="label">${p.id}</div><h3>${p.name}</h3></div><div><span class="price">${money(p.price)}</span><button class="btn" data-add="${p.id}" style="float:right">加入</button></div></article>`).join('')}</section></main>${state.cart.length?`<button class="cartbar" data-view="cart"><span>${state.cart.reduce((s,x)=>s+x.qty,0)}件餐點</span><strong>${money(cartTotal())}　查看購物車</strong></button>`:''}`}
function cart(){return `${header('購物車','核對餐點')}<main class="content"><section class="list">${state.cart.length?state.cart.map(x=>`<article class="card order-row"><div><strong>${x.name}</strong><div class="label">${x.id} · 數量 ${x.qty}</div></div><strong>${money(x.price*x.qty)}</strong></article>`).join(''):'<div class="empty">購物車未有餐點</div>'}</section>${state.cart.length?`<div class="section-title"><h2>合計</h2><strong>${money(cartTotal())}</strong></div><button class="btn primary" data-view="checkout" style="width:100%">確認訂單</button><button class="btn" data-view="menu" style="width:100%;margin-top:10px">繼續選購</button>`:''}</main>`}
function checkout(){return `${header('確認訂單','來源、付款及取餐資料')}<main class="content"><section class="list"><article class="card"><div class="label">訂單來源</div><strong>現場外賣</strong></article><article class="card"><div class="label">付款方式</div><strong>現金</strong></article><article class="card"><div class="label">取餐時間</div><strong>盡快準備</strong></article><article class="card order-row"><strong>訂單總額</strong><strong>${money(cartTotal())}</strong></article></section><button class="btn primary" id="submit-order" style="width:100%;margin-top:14px">正式建立訂單</button></main>`}
function generic(title,text){return `${header(title)}<main class="content"><article class="card"><p>${text}</p></article></main>`}
function render(){let page=state.view==='dashboard'?dashboard():state.view==='menu'?menu():state.view==='cart'?cart():state.view==='checkout'?checkout():state.view==='orders'?generic('訂單','網站、App、現場、電話、WhatsApp及平台訂單會集中顯示。'):state.view==='dine'?generic('堂食','堂食開枱、加單、付款及結枱入口。'):generic('更多','售罄、預約、報表、打印工作及系統設定。');document.querySelector('#app').innerHTML=`<div class="app">${page}${!['cart','checkout'].includes(state.view)?navHtml():''}</div>`;bind()}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addProduct(b.dataset.add));document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;render()});const submit=document.querySelector('#submit-order');if(submit)submit.onclick=()=>{state.cart=[];state.view='orders';render()}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
render();